apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  template:
    metadata:
      name: vault
      labels:
        app.kubernetes.io/name: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault-enterprise:latest
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-ec'
                - vault status -tls-skip-verify
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 5 && kill -SIGTERM $(pidof vault)
          env:
            - name: VAULT_ADDR
              value: 'http://127.0.0.1:8200'
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: root
            - name: VAULT_TOKEN
              value: root
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
      restartPolicy: Always
      serviceAccountName: vault
